// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _fir_HH_
#define _fir_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct fir : public sc_module {
    // Port declarations 9
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<19> > y_V;
    sc_out< sc_logic > y_V_ap_vld;
    sc_in< sc_lv<8> > x_V;


    // Module declarations
    fir(sc_module_name name);
    SC_HAS_PROCESS(fir);

    ~fir();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > shift_reg_V_6;
    sc_signal< sc_lv<8> > shift_reg_V_5;
    sc_signal< sc_lv<8> > shift_reg_V_4;
    sc_signal< sc_lv<8> > shift_reg_V_3;
    sc_signal< sc_lv<8> > shift_reg_V_2;
    sc_signal< sc_lv<8> > shift_reg_V_1;
    sc_signal< sc_lv<8> > shift_reg_V_0;
    sc_signal< sc_lv<14> > r_V_8_fu_229_p2;
    sc_signal< sc_lv<14> > r_V_8_reg_333;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<11> > p_shl4_fu_79_p3;
    sc_signal< sc_lv<12> > p_shl4_cast_fu_87_p1;
    sc_signal< sc_lv<12> > lhs_V_fu_75_p1;
    sc_signal< sc_lv<11> > r_V_fu_57_p3;
    sc_signal< sc_lv<12> > r_V_1_fu_91_p2;
    sc_signal< sc_lv<13> > rhs_V_fu_101_p1;
    sc_signal< sc_lv<13> > lhs_V_1_fu_97_p1;
    sc_signal< sc_lv<11> > p_shl2_fu_121_p3;
    sc_signal< sc_lv<9> > p_shl3_fu_133_p3;
    sc_signal< sc_lv<12> > p_shl2_cast_fu_129_p1;
    sc_signal< sc_lv<12> > p_shl3_cast_fu_141_p1;
    sc_signal< sc_lv<13> > r_V_2_fu_105_p2;
    sc_signal< sc_lv<12> > r_V_3_fu_145_p2;
    sc_signal< sc_lv<14> > rhs_V_1_fu_155_p1;
    sc_signal< sc_lv<14> > lhs_V_2_fu_151_p1;
    sc_signal< sc_lv<10> > p_shl1_fu_179_p3;
    sc_signal< sc_lv<11> > lhs_V_5_cast2_fu_175_p1;
    sc_signal< sc_lv<11> > p_shl1_cast_fu_187_p1;
    sc_signal< sc_lv<11> > r_V_5_fu_191_p2;
    sc_signal< sc_lv<14> > rhs_V_2_cast_fu_197_p1;
    sc_signal< sc_lv<14> > r_V_4_fu_159_p2;
    sc_signal< sc_lv<10> > r_V_7_fu_217_p3;
    sc_signal< sc_lv<14> > rhs_V_3_cast_fu_225_p1;
    sc_signal< sc_lv<14> > r_V_6_fu_201_p2;
    sc_signal< sc_lv<10> > p_shl_fu_249_p3;
    sc_signal< sc_lv<11> > p_shl_cast_fu_257_p1;
    sc_signal< sc_lv<11> > lhs_V_9_cast1_fu_245_p1;
    sc_signal< sc_lv<11> > r_V_9_fu_261_p2;
    sc_signal< sc_lv<12> > r_V_9_cast_fu_267_p1;
    sc_signal< sc_lv<15> > rhs_V_4_cast_fu_274_p1;
    sc_signal< sc_lv<15> > lhs_V_10_cast_fu_271_p1;
    sc_signal< sc_lv<9> > r_V_11_fu_294_p3;
    sc_signal< sc_lv<15> > rhs_V_5_cast_fu_302_p1;
    sc_signal< sc_lv<15> > r_V_10_fu_278_p2;
    sc_signal< sc_lv<15> > rhs_V_6_cast_fu_318_p1;
    sc_signal< sc_lv<15> > r_V_12_fu_306_p2;
    sc_signal< sc_lv<15> > r_V_13_fu_322_p2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_lhs_V_10_cast_fu_271_p1();
    void thread_lhs_V_1_fu_97_p1();
    void thread_lhs_V_2_fu_151_p1();
    void thread_lhs_V_5_cast2_fu_175_p1();
    void thread_lhs_V_9_cast1_fu_245_p1();
    void thread_lhs_V_fu_75_p1();
    void thread_p_shl1_cast_fu_187_p1();
    void thread_p_shl1_fu_179_p3();
    void thread_p_shl2_cast_fu_129_p1();
    void thread_p_shl2_fu_121_p3();
    void thread_p_shl3_cast_fu_141_p1();
    void thread_p_shl3_fu_133_p3();
    void thread_p_shl4_cast_fu_87_p1();
    void thread_p_shl4_fu_79_p3();
    void thread_p_shl_cast_fu_257_p1();
    void thread_p_shl_fu_249_p3();
    void thread_r_V_10_fu_278_p2();
    void thread_r_V_11_fu_294_p3();
    void thread_r_V_12_fu_306_p2();
    void thread_r_V_13_fu_322_p2();
    void thread_r_V_1_fu_91_p2();
    void thread_r_V_2_fu_105_p2();
    void thread_r_V_3_fu_145_p2();
    void thread_r_V_4_fu_159_p2();
    void thread_r_V_5_fu_191_p2();
    void thread_r_V_6_fu_201_p2();
    void thread_r_V_7_fu_217_p3();
    void thread_r_V_8_fu_229_p2();
    void thread_r_V_9_cast_fu_267_p1();
    void thread_r_V_9_fu_261_p2();
    void thread_r_V_fu_57_p3();
    void thread_rhs_V_1_fu_155_p1();
    void thread_rhs_V_2_cast_fu_197_p1();
    void thread_rhs_V_3_cast_fu_225_p1();
    void thread_rhs_V_4_cast_fu_274_p1();
    void thread_rhs_V_5_cast_fu_302_p1();
    void thread_rhs_V_6_cast_fu_318_p1();
    void thread_rhs_V_fu_101_p1();
    void thread_y_V();
    void thread_y_V_ap_vld();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
