-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity svm_top is
port (
    class_hw0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    class_hw1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    class_hw2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    class_hw3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    x0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    x0_ce0 : OUT STD_LOGIC;
    x0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x0_we0 : OUT STD_LOGIC;
    x0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    x0_ce1 : OUT STD_LOGIC;
    x0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    x0_we1 : OUT STD_LOGIC;
    x1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    x1_ce0 : OUT STD_LOGIC;
    x1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x1_we0 : OUT STD_LOGIC;
    x1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    x1_ce1 : OUT STD_LOGIC;
    x1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    x1_we1 : OUT STD_LOGIC;
    x2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    x2_ce0 : OUT STD_LOGIC;
    x2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_we0 : OUT STD_LOGIC;
    x2_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    x2_ce1 : OUT STD_LOGIC;
    x2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    x2_we1 : OUT STD_LOGIC;
    x3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    x3_ce0 : OUT STD_LOGIC;
    x3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x3_we0 : OUT STD_LOGIC;
    x3_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    x3_ce1 : OUT STD_LOGIC;
    x3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    x3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    x3_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    class_hw0_ap_vld : OUT STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    class_hw1_ap_vld : OUT STD_LOGIC;
    class_hw2_ap_vld : OUT STD_LOGIC;
    class_hw3_ap_vld : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of svm_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "svm_top,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.317400,HLS_SYN_LAT=175969,HLS_SYN_TPT=175970,HLS_SYN_MEM=272,HLS_SYN_DSP=200,HLS_SYN_FF=16256,HLS_SYN_LUT=30218,HLS_VERSION=2018_2}";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal svm5_U0_ap_start : STD_LOGIC;
    signal svm5_U0_ap_done : STD_LOGIC;
    signal svm5_U0_ap_continue : STD_LOGIC;
    signal svm5_U0_ap_idle : STD_LOGIC;
    signal svm5_U0_ap_ready : STD_LOGIC;
    signal svm5_U0_class_hw : STD_LOGIC_VECTOR (15 downto 0);
    signal svm5_U0_class_hw_ap_vld : STD_LOGIC;
    signal svm5_U0_x_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal svm5_U0_x_ce0 : STD_LOGIC;
    signal svm5_U0_x_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal svm5_U0_x_ce1 : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal svm6_U0_ap_start : STD_LOGIC;
    signal svm6_U0_ap_done : STD_LOGIC;
    signal svm6_U0_ap_continue : STD_LOGIC;
    signal svm6_U0_ap_idle : STD_LOGIC;
    signal svm6_U0_ap_ready : STD_LOGIC;
    signal svm6_U0_class_hw : STD_LOGIC_VECTOR (15 downto 0);
    signal svm6_U0_class_hw_ap_vld : STD_LOGIC;
    signal svm6_U0_x_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal svm6_U0_x_ce0 : STD_LOGIC;
    signal svm6_U0_x_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal svm6_U0_x_ce1 : STD_LOGIC;
    signal svm7_U0_ap_start : STD_LOGIC;
    signal svm7_U0_ap_done : STD_LOGIC;
    signal svm7_U0_ap_continue : STD_LOGIC;
    signal svm7_U0_ap_idle : STD_LOGIC;
    signal svm7_U0_ap_ready : STD_LOGIC;
    signal svm7_U0_class_hw : STD_LOGIC_VECTOR (15 downto 0);
    signal svm7_U0_class_hw_ap_vld : STD_LOGIC;
    signal svm7_U0_x_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal svm7_U0_x_ce0 : STD_LOGIC;
    signal svm7_U0_x_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal svm7_U0_x_ce1 : STD_LOGIC;
    signal svm_U0_ap_start : STD_LOGIC;
    signal svm_U0_ap_done : STD_LOGIC;
    signal svm_U0_ap_continue : STD_LOGIC;
    signal svm_U0_ap_idle : STD_LOGIC;
    signal svm_U0_ap_ready : STD_LOGIC;
    signal svm_U0_class_hw : STD_LOGIC_VECTOR (15 downto 0);
    signal svm_U0_class_hw_ap_vld : STD_LOGIC;
    signal svm_U0_x_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal svm_U0_x_ce0 : STD_LOGIC;
    signal svm_U0_x_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal svm_U0_x_ce1 : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_svm5_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_svm5_U0_ap_ready : STD_LOGIC;
    signal svm5_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_svm6_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_svm6_U0_ap_ready : STD_LOGIC;
    signal svm6_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_svm7_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_svm7_U0_ap_ready : STD_LOGIC;
    signal svm7_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_svm_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_svm_U0_ap_ready : STD_LOGIC;
    signal svm_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal svm5_U0_start_full_n : STD_LOGIC;
    signal svm5_U0_start_write : STD_LOGIC;
    signal svm6_U0_start_full_n : STD_LOGIC;
    signal svm6_U0_start_write : STD_LOGIC;
    signal svm7_U0_start_full_n : STD_LOGIC;
    signal svm7_U0_start_write : STD_LOGIC;
    signal svm_U0_start_full_n : STD_LOGIC;
    signal svm_U0_start_write : STD_LOGIC;

    component svm5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        class_hw : OUT STD_LOGIC_VECTOR (15 downto 0);
        class_hw_ap_vld : OUT STD_LOGIC;
        x_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        x_ce0 : OUT STD_LOGIC;
        x_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        x_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        x_ce1 : OUT STD_LOGIC;
        x_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component svm6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        class_hw : OUT STD_LOGIC_VECTOR (15 downto 0);
        class_hw_ap_vld : OUT STD_LOGIC;
        x_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        x_ce0 : OUT STD_LOGIC;
        x_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        x_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        x_ce1 : OUT STD_LOGIC;
        x_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component svm7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        class_hw : OUT STD_LOGIC_VECTOR (15 downto 0);
        class_hw_ap_vld : OUT STD_LOGIC;
        x_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        x_ce0 : OUT STD_LOGIC;
        x_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        x_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        x_ce1 : OUT STD_LOGIC;
        x_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component svm IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        class_hw : OUT STD_LOGIC_VECTOR (15 downto 0);
        class_hw_ap_vld : OUT STD_LOGIC;
        x_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        x_ce0 : OUT STD_LOGIC;
        x_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        x_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        x_ce1 : OUT STD_LOGIC;
        x_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    svm5_U0 : component svm5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => svm5_U0_ap_start,
        ap_done => svm5_U0_ap_done,
        ap_continue => svm5_U0_ap_continue,
        ap_idle => svm5_U0_ap_idle,
        ap_ready => svm5_U0_ap_ready,
        class_hw => svm5_U0_class_hw,
        class_hw_ap_vld => svm5_U0_class_hw_ap_vld,
        x_address0 => svm5_U0_x_address0,
        x_ce0 => svm5_U0_x_ce0,
        x_q0 => x0_q0,
        x_address1 => svm5_U0_x_address1,
        x_ce1 => svm5_U0_x_ce1,
        x_q1 => x0_q1);

    svm6_U0 : component svm6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => svm6_U0_ap_start,
        ap_done => svm6_U0_ap_done,
        ap_continue => svm6_U0_ap_continue,
        ap_idle => svm6_U0_ap_idle,
        ap_ready => svm6_U0_ap_ready,
        class_hw => svm6_U0_class_hw,
        class_hw_ap_vld => svm6_U0_class_hw_ap_vld,
        x_address0 => svm6_U0_x_address0,
        x_ce0 => svm6_U0_x_ce0,
        x_q0 => x1_q0,
        x_address1 => svm6_U0_x_address1,
        x_ce1 => svm6_U0_x_ce1,
        x_q1 => x1_q1);

    svm7_U0 : component svm7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => svm7_U0_ap_start,
        ap_done => svm7_U0_ap_done,
        ap_continue => svm7_U0_ap_continue,
        ap_idle => svm7_U0_ap_idle,
        ap_ready => svm7_U0_ap_ready,
        class_hw => svm7_U0_class_hw,
        class_hw_ap_vld => svm7_U0_class_hw_ap_vld,
        x_address0 => svm7_U0_x_address0,
        x_ce0 => svm7_U0_x_ce0,
        x_q0 => x2_q0,
        x_address1 => svm7_U0_x_address1,
        x_ce1 => svm7_U0_x_ce1,
        x_q1 => x2_q1);

    svm_U0 : component svm
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => svm_U0_ap_start,
        ap_done => svm_U0_ap_done,
        ap_continue => svm_U0_ap_continue,
        ap_idle => svm_U0_ap_idle,
        ap_ready => svm_U0_ap_ready,
        class_hw => svm_U0_class_hw,
        class_hw_ap_vld => svm_U0_class_hw_ap_vld,
        x_address0 => svm_U0_x_address0,
        x_ce0 => svm_U0_x_ce0,
        x_q0 => x3_q0,
        x_address1 => svm_U0_x_address1,
        x_ce1 => svm_U0_x_ce1,
        x_q1 => x3_q1);





    ap_sync_reg_svm5_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_svm5_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_svm5_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_svm5_U0_ap_ready <= ap_sync_svm5_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_svm6_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_svm6_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_svm6_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_svm6_U0_ap_ready <= ap_sync_svm6_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_svm7_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_svm7_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_svm7_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_svm7_U0_ap_ready <= ap_sync_svm7_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_svm_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_svm_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_svm_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_svm_U0_ap_ready <= ap_sync_svm_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    svm5_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((svm5_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                svm5_U0_ap_ready_count <= std_logic_vector(unsigned(svm5_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (svm5_U0_ap_ready = ap_const_logic_1))) then 
                svm5_U0_ap_ready_count <= std_logic_vector(unsigned(svm5_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    svm6_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((svm6_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                svm6_U0_ap_ready_count <= std_logic_vector(unsigned(svm6_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (svm6_U0_ap_ready = ap_const_logic_1))) then 
                svm6_U0_ap_ready_count <= std_logic_vector(unsigned(svm6_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    svm7_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((svm7_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                svm7_U0_ap_ready_count <= std_logic_vector(unsigned(svm7_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (svm7_U0_ap_ready = ap_const_logic_1))) then 
                svm7_U0_ap_ready_count <= std_logic_vector(unsigned(svm7_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    svm_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((svm_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                svm_U0_ap_ready_count <= std_logic_vector(unsigned(svm_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (svm_U0_ap_ready = ap_const_logic_1))) then 
                svm_U0_ap_ready_count <= std_logic_vector(unsigned(svm_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;
    ap_done <= ap_sync_done;
    ap_idle <= (svm_U0_ap_idle and svm7_U0_ap_idle and svm6_U0_ap_idle and svm5_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_continue <= ap_sync_done;
    ap_sync_done <= (svm_U0_ap_done and svm7_U0_ap_done and svm6_U0_ap_done and svm5_U0_ap_done);
    ap_sync_ready <= (ap_sync_svm_U0_ap_ready and ap_sync_svm7_U0_ap_ready and ap_sync_svm6_U0_ap_ready and ap_sync_svm5_U0_ap_ready);
    ap_sync_svm5_U0_ap_ready <= (svm5_U0_ap_ready or ap_sync_reg_svm5_U0_ap_ready);
    ap_sync_svm6_U0_ap_ready <= (svm6_U0_ap_ready or ap_sync_reg_svm6_U0_ap_ready);
    ap_sync_svm7_U0_ap_ready <= (svm7_U0_ap_ready or ap_sync_reg_svm7_U0_ap_ready);
    ap_sync_svm_U0_ap_ready <= (svm_U0_ap_ready or ap_sync_reg_svm_U0_ap_ready);
    class_hw0 <= svm5_U0_class_hw;
    class_hw0_ap_vld <= svm5_U0_class_hw_ap_vld;
    class_hw1 <= svm6_U0_class_hw;
    class_hw1_ap_vld <= svm6_U0_class_hw_ap_vld;
    class_hw2 <= svm7_U0_class_hw;
    class_hw2_ap_vld <= svm7_U0_class_hw_ap_vld;
    class_hw3 <= svm_U0_class_hw;
    class_hw3_ap_vld <= svm_U0_class_hw_ap_vld;
    svm5_U0_ap_continue <= ap_sync_done;
    svm5_U0_ap_start <= ((ap_sync_reg_svm5_U0_ap_ready xor ap_const_logic_1) and ap_start);
    svm5_U0_start_full_n <= ap_const_logic_1;
    svm5_U0_start_write <= ap_const_logic_0;
    svm6_U0_ap_continue <= ap_sync_done;
    svm6_U0_ap_start <= ((ap_sync_reg_svm6_U0_ap_ready xor ap_const_logic_1) and ap_start);
    svm6_U0_start_full_n <= ap_const_logic_1;
    svm6_U0_start_write <= ap_const_logic_0;
    svm7_U0_ap_continue <= ap_sync_done;
    svm7_U0_ap_start <= ((ap_sync_reg_svm7_U0_ap_ready xor ap_const_logic_1) and ap_start);
    svm7_U0_start_full_n <= ap_const_logic_1;
    svm7_U0_start_write <= ap_const_logic_0;
    svm_U0_ap_continue <= ap_sync_done;
    svm_U0_ap_start <= ((ap_sync_reg_svm_U0_ap_ready xor ap_const_logic_1) and ap_start);
    svm_U0_start_full_n <= ap_const_logic_1;
    svm_U0_start_write <= ap_const_logic_0;
    x0_address0 <= svm5_U0_x_address0;
    x0_address1 <= svm5_U0_x_address1;
    x0_ce0 <= svm5_U0_x_ce0;
    x0_ce1 <= svm5_U0_x_ce1;
    x0_d0 <= ap_const_lv32_0;
    x0_d1 <= ap_const_lv32_0;
    x0_we0 <= ap_const_logic_0;
    x0_we1 <= ap_const_logic_0;
    x1_address0 <= svm6_U0_x_address0;
    x1_address1 <= svm6_U0_x_address1;
    x1_ce0 <= svm6_U0_x_ce0;
    x1_ce1 <= svm6_U0_x_ce1;
    x1_d0 <= ap_const_lv32_0;
    x1_d1 <= ap_const_lv32_0;
    x1_we0 <= ap_const_logic_0;
    x1_we1 <= ap_const_logic_0;
    x2_address0 <= svm7_U0_x_address0;
    x2_address1 <= svm7_U0_x_address1;
    x2_ce0 <= svm7_U0_x_ce0;
    x2_ce1 <= svm7_U0_x_ce1;
    x2_d0 <= ap_const_lv32_0;
    x2_d1 <= ap_const_lv32_0;
    x2_we0 <= ap_const_logic_0;
    x2_we1 <= ap_const_logic_0;
    x3_address0 <= svm_U0_x_address0;
    x3_address1 <= svm_U0_x_address1;
    x3_ce0 <= svm_U0_x_ce0;
    x3_ce1 <= svm_U0_x_ce1;
    x3_d0 <= ap_const_lv32_0;
    x3_d1 <= ap_const_lv32_0;
    x3_we0 <= ap_const_logic_0;
    x3_we1 <= ap_const_logic_0;
end behav;
