# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Afroditi/Documents/8thSemester/dvlsi/Lab5/dvlsi2021_lab5/dvlsi2021_ask5_prj/dvlsi2021_ask5_prj.srcs/sources_1/bd/design_1/ip/design_1_PS_ARM_0/design_1_PS_ARM_0.xci
# IP: The module: 'design_1_PS_ARM_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Afroditi/Documents/8thSemester/dvlsi/Lab5/dvlsi2021_lab5/dvlsi2021_ask5_prj/dvlsi2021_ask5_prj.srcs/sources_1/bd/design_1/ip/design_1_PS_ARM_0/design_1_PS_ARM_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PS_ARM_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Afroditi/Documents/8thSemester/dvlsi/Lab5/dvlsi2021_lab5/dvlsi2021_ask5_prj/dvlsi2021_ask5_prj.srcs/sources_1/bd/design_1/ip/design_1_PS_ARM_0/design_1_PS_ARM_0.xci
# IP: The module: 'design_1_PS_ARM_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Afroditi/Documents/8thSemester/dvlsi/Lab5/dvlsi2021_lab5/dvlsi2021_ask5_prj/dvlsi2021_ask5_prj.srcs/sources_1/bd/design_1/ip/design_1_PS_ARM_0/design_1_PS_ARM_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PS_ARM_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
